Logic initialisation + TG bot addition (#3)
profcomff/aciniformes-project pull request #5
Opened 2023-04-10 11:06 UTC by Wudext

2023-05-14 01:21 UTC, grigoriev-semyon requested changes
Пробежался по коду, очень много комментариев, так что оставлю в общем формате пунктов, которые надо исправить
1. Очень много кода, который остался от предыдущих версий и больше не используется
2. async/await используется очень плохо - в тех местах где он замедляет - он есть, а в тех где он нужен по логике - его нет
3. Нет документации
4. Проект сделан не по шаблону
5. Отсутствует докерфайл и прочие плюшки шаблонизации

2023-05-14 01:24 UTC, grigoriev-semyon commented on tests/ping_service/service/test_scheduler.py
> +    )
а почему не переменной просто?

2023-05-14 01:25 UTC, grigoriev-semyon commented on tests/ping_service/service/test_scheduler.py
> +            "address": "https://www.python.org",
а зачем пинговать питон когда можно пинговать себя?

2023-05-14 01:26 UTC, grigoriev-semyon commented on tests/ping_service/service/test_scheduler.py
> +            "address": "https://www.python.org",
тесты зависимые от других ресурсов это плохо

2023-05-14 01:27 UTC, grigoriev-semyon commented on tests/ping_service/conftest.py
> +def dbsession() -> Session:
тайп хинт неправильный

2023-05-14 01:28 UTC, grigoriev-semyon commented on tests/ping_service/conftest.py
> +    BaseModel.metadata.create_all(bind=engine)
не надо создавать и удалять постоянно БД

2023-05-14 01:29 UTC, grigoriev-semyon commented on requirements.txt
> +aiogram~=2.25.1
го без версий

2023-05-14 01:31 UTC, grigoriev-semyon commented on ping/service/crud.py
> +        return httpx.get(f"{self.backend_url}/alert").json()
не понимаю смысла всех этих асинков если внутри синхронные вызовы

2023-05-14 01:31 UTC, grigoriev-semyon commented on ping/service/crud.py
> +        return list(self.alert_repo.values())
не понимаю смысла всех этих асинков если внутри синхронные вызовы

2023-05-14 01:32 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +        del self.scheduler[fetcher.id_]
не понимаю смысла асинков если это неблокирующие операции

2023-05-14 01:32 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +        self.scheduler["started"] = False
не понимаю смысла асинков если это неблокирующие операции

2023-05-14 01:33 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +        httpx.post(f"{settings.BOT_URL}/alert", json=metric_log.json())
не понимаю смысла всех этих асинков если внутри синхронные вызовы

2023-05-14 01:33 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +    async def write_alert(self, metric_log: MetricCreateSchema, alert: AlertCreateSchema):
здесь тоже асинки выставлены нелогично

2023-05-14 01:33 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +
тоже бесполезный асинк

2023-05-14 01:34 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +        except:
except BaseException? так нельзя

2023-05-14 01:34 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +            return
return await

2023-05-14 01:35 UTC, grigoriev-semyon commented on ping/service/scheduler.py
> +            ok=True if res and res.status_code == 200 else False,
почему только 200?

2023-05-14 01:35 UTC, grigoriev-semyon commented on tests/backend/api/conftest.py
> +    return client
в новых версиях либы это не нужно

2023-05-14 01:36 UTC, grigoriev-semyon commented on ping/service/bootstrap.py
> +    return CrudService()
го тернар

2023-05-14 01:37 UTC, grigoriev-semyon commented on ping/service/bootstrap.py
> +    return ApSchedulerService(crud_service())
го тернар

2023-05-14 01:38 UTC, grigoriev-semyon commented on ping/service/crud.py
> +    id_incr = 0
зачем этот инкремент? 
давай без него, сбивает с толку

2023-05-14 01:39 UTC, grigoriev-semyon commented on ping/service/crud.py
> +                "address": "https://www.python.org",
почему пингуем питон? почему не себя?

2023-05-14 01:40 UTC, grigoriev-semyon commented on ping/service/crud.py
> +        self.backend_url: str = get_settings().BACKEND_URL
переменная не объявлена вверху для линтера

2023-05-14 01:41 UTC, grigoriev-semyon commented on migrator/versions/febba504289a_init.py
> +    # ### commands auto generated by Alembic - please adjust! ###
удали комменты

2023-05-14 01:41 UTC, grigoriev-semyon commented on migrator/env.py
переименуй папку в migrations

2023-05-14 01:42 UTC, grigoriev-semyon commented on aciniformes_backend/settings.py
>      PWD_CONTEXT = CryptContext(schemes=["bcrypt"], deprecated="auto")
It's the only usage in All Places

2023-05-14 01:45 UTC, grigoriev-semyon commented on aciniformes_backend/serivce/base.py
в этом файле у всех классов общих полей больше чем 2
почему get_by_id не в интерфейсе?

2023-05-14 01:47 UTC, grigoriev-semyon commented on aciniformes_backend/routes/fetcher.py
> +    type_: FetcherType
оно работает без алиаса? с подчеркиванием то

2023-05-14 01:47 UTC, grigoriev-semyon commented on aciniformes_backend/routes/fetcher.py
> +logger = logging.getLogger(__name__)
не вижу использований

2023-05-14 01:50 UTC, grigoriev-semyon requested changes
В общем исправь то что я написал в общем комменте и то что в отдельных
Еще @dyakovri поревьюит потом
Запустим как раз, посмотрим как работает

2023-05-14 01:53 UTC, grigoriev-semyon commented on requirements.txt
> +aiogram~=2.25.1
некоторые библиотеки надо выпилить отсюда потому что они не использованы в проекте

2023-05-15 09:10 UTC, Wudext commented on tests/ping_service/service/test_scheduler.py
> +    )
С ним так проще будет работать потом

2023-05-15 09:23 UTC, Wudext commented on aciniformes_backend/routes/fetcher.py
> +    type_: FetcherType
Вроде работает

2023-05-15 13:09 UTC, grigoriev-semyon commented on aciniformes_backend/routes/fetcher.py
> +    type_: FetcherType
и какой словарь отображается в сваггере?

2023-05-27 14:30 UTC, grigoriev-semyon requested changes
ну если работает то жить мб и можно

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/alert.py
> +    logger.info(f"Someone triggered create_schema")
зачем если есть логи фастапи?

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/alert.py
> +    logger.info(f"Someone triggered get_schemas")
зачем если есть логи фастапи?

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/alert.py
> +    logger.info(f"Someone triggered get_schema")
зачем если есть логи фастапи?

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/alert.py
> +    logger.info(f"Someone triggered update_schema")
зачем если есть логи фастапи?

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/alert.py
> +    logger.info(f"Someone triggered delete_schema")
зачем если есть логи фастапи?

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/reciever.py
> +    logger.info(f"Someone triggered get_receivers")
зачем если есть логи фастапи?

ко всем остальным тот же коммент

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/serivce/bootstrap.py
>          return PgFetcherService(db.session)
возвращать что то в менеджере не оч

2023-05-27 14:30 UTC, grigoriev-semyon commented on aciniformes_backend/serivce/receiver.py
> +    def get_by_id(self, id_: int) -> Type[db_models.Receiver]:
async

2023-05-27 16:56 UTC, Wudext commented on aciniformes_backend/serivce/bootstrap.py
>          return PgFetcherService(db.session)
Если убрать то все поломается

2023-05-27 16:56 UTC, Wudext commented on aciniformes_backend/routes/alert/reciever.py
> +    logger.info(f"Someone triggered get_receivers")
Убрал

2023-05-29 13:44 UTC, Wudext commented on Makefile
> +	source ./venv/bin/activate && uvicorn --reload --log-config logging_dev.conf pinger_backend.routes.base:app
Тут только бэк запускаться должен, поправил

2023-07-12 09:16 UTC, grigoriev-semyon requested changes
ping'а нет, как будет - досмотрю

2023-07-12 09:19 UTC, grigoriev-semyon requested changes
миграции куда то пропали
тесты падают 
нет докерфайла для пингера

2023-07-15 17:11 UTC, Wudext commented on aciniformes_backend/routes/fetcher.py
> +    type_: FetcherType
{
  "type_": "get",
  "address": "string",
  "fetch_data": "string",
  "delay_ok": 0,
  "delay_fail": 0
}

2023-07-24 20:39 UTC, Temmmmmo reviewed
Описание к ПРу

2023-07-24 20:39 UTC, Temmmmmo commented on aciniformes_backend/routes/alert/reciever.py
>      id_ = await receiver.create(create_schema.dict())
`.dict() ` устарел используй `model_dump()` - Pydantic v2

2023-07-24 20:39 UTC, Temmmmmo commented on aciniformes_backend/routes/fetcher.py
> +    type_: FetcherType | None
Pv2

2023-07-24 20:39 UTC, Temmmmmo commented on aciniformes_backend/serivce/alert.py
>      async def update(self, id_: int, item: dict) -> db_models.Alert:
Доку к методу

2023-07-24 20:39 UTC, Temmmmmo commented on migrations/versions/febba504289a_init.py
> +        sa.Column('create_ts', sa.DateTime(), nullable=False),
`nullable=False` не упадет? Думаю, надо сделать нуллбл, потом запрос написать, чтобы current_timestamp проставить в поле, а потом уже сделать не нуллбл.

2023-07-27 12:54 UTC, grigoriev-semyon commented on migrations/versions/febba504289a_init.py
> +        sa.Column('create_ts', sa.DateTime(), nullable=False),
не упадет
это же первая миграция
там нет данных

2023-07-27 13:00 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/alert.py
> +    data: dict[str, str | list | dict | bool | int | float]
просто любой

2023-07-27 13:01 UTC, grigoriev-semyon commented on aciniformes_backend/routes/alert/alert.py
> +    data: dict[str, str | list | dict | bool | int | float]
ну можно чуть ограничить

2023-07-27 13:33 UTC, Temmmmmo approved these changes

2023-07-27 13:33 UTC, grigoriev-semyon approved these changes

2023-07-27 13:34 UTC, merged